version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    groups:
      django-channels:
        patterns:
          - "django"
          - "channels"
          - "channels-redis"
          - "daphne"
          - "django-debug-toolbar"
          - "django-extensions"
          - "django-htmx"
      test-tools:
        patterns:
          - "pytest*"
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
