x-app: &app
  image: asacx
  build:
    context: .
  volumes:
    - .:/app
  restart: unless-stopped
  depends_on:
    db:
      condition: service_healthy
    cache:
      condition: service_healthy
    migrate:
      condition: service_completed_successfully

services:
  migrate:
    image: asacx
    build:
      context: .
    volumes:
      - .:/app
    command: python manage.py migrate --noinput
    depends_on:
      db:
        condition: service_healthy
  server:
    <<: *app
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000
  channel-master:
    <<: *app
    command: watchmedo auto-restart --directory=/app --ignore-pattern=*sqlite3 --pattern=*.py --recursive -- python manage.py custom_runworker *
    environment:
      - CHANNELS_WORKER_MASTER=1
  channel-worker:
    extends:
      service: channel-master
    environment:
      - CHANNELS_WORKER_MASTER=0
    deploy:
      mode: replicated
      replicas: 3
  cache:
    image: redis:7
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: django_password
      POSTGRES_USER: django_user
      POSTGRES_DB: django_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U django_user -d django_db"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  pgdata:
