# Generated by Django 4.1.5 on 2023-01-31 23:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Party",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("started_at", models.DateTimeField()),
                ("closed_at", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="UserRoundAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "field",
                    models.CharField(
                        choices=[
                            ("name", "name"),
                            ("country", "country"),
                            ("city", "city"),
                            ("COLOR", "COLOR"),
                            ("thing", "thing"),
                            ("animal", "animal"),
                        ],
                        max_length=50,
                    ),
                ),
                ("value", models.CharField(max_length=50)),
                ("saved_at", models.DateTimeField(auto_now=True)),
                (
                    "round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.party"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("round", "user", "field")},
            },
        ),
        migrations.CreateModel(
            name="PartyRound",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("letter", models.CharField(max_length=1)),
                ("started_at", models.DateTimeField()),
                ("closed_at", models.DateTimeField()),
                (
                    "party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.party"
                    ),
                ),
            ],
            options={
                "unique_together": {("party", "letter")},
            },
        ),
    ]
