# Generated by Django 4.1.5 on 2023-01-31 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="party",
            name="closed_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="party",
            name="started_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
