# Generated by Django 4.1.5 on 2023-04-29 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_party_closed_at_alter_party_started_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partyround",
            name="closed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
