# Generated by Django 4.2.3 on 2023-07-15 20:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_partyround_closed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="partyround",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default="2023-01-01"),
            preserve_default=False,
        ),
    ]
