# Generated by Django 4.2.3 on 2023-07-15 21:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_partyround_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partyround",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
