# Generated by Django 4.2.3 on 2023-07-15 21:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_alter_partyround_started_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="party",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default="2023-01-01"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="party",
            name="closed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="party",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="partyround",
            name="started_at",
            field=models.DateTimeField(auto_now_add=True, default="2023-01-01"),
            preserve_default=False,
        ),
    ]
