# Generated by Django 4.2.3 on 2024-01-21 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_party_joined_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userroundanswer',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.partyround'),
        ),
    ]
