# Generated by Django 4.2.3 on 2024-02-01 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_userroundanswer_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='userroundanswer',
            name='scored_points',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
