# Generated by Django 4.2.3 on 2026-09-29 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_close_finished_parties'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='waiting_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
