# Generated by Django 4.2.3 on 2026-09-29 13:10

import datetime

from django.db import migrations, models
import django.utils.timezone


def backfill_deadlines(apps, schema_editor):
    PartyRound = apps.get_model("core", "PartyRound")
    for round in PartyRound.objects.select_related("party"):
        duration = datetime.timedelta(seconds=round.party.max_round_duration)
        round.deadline_at = round.started_at + duration
        round.save(update_fields=["deadline_at"])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_answer_verdicts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partyround',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='partyround',
            name='deadline_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.RunPython(backfill_deadlines, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='partyround',
            name='deadline_at',
            field=models.DateTimeField(),
        ),
    ]
