# Generated by Django 5.2.17 on 2026-09-29 14:52

from django.db import migrations, models
from django.db.models import F, Window
from django.db.models.functions import RowNumber


def backfill_numbers(apps, schema_editor):
    PartyRound = apps.get_model("core", "PartyRound")
    numbered = PartyRound.objects.annotate(
        position=Window(
            RowNumber(),
            partition_by=[F("party_id")],
            order_by=[F("started_at").asc(), F("id").asc()],
        )
    ).values_list("id", "position")
    rounds = [PartyRound(id=id, number=position) for id, position in numbered]
    PartyRound.objects.bulk_update(rounds, ["number"], batch_size=1000)


def backfill_closed_reasons(apps, schema_editor):
    PartyRound = apps.get_model("core", "PartyRound")
    closed = PartyRound.objects.filter(closed_at__isnull=False)
    closed.filter(closed_at__lt=F("deadline_at")).update(closed_reason="stop")
    closed.filter(closed_at__gte=F("deadline_at")).update(closed_reason="timeout")


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0021_spanish_labels"),
    ]

    operations = [
        migrations.AddField(
            model_name="partyround",
            name="number",
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.RunPython(backfill_numbers, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="partyround",
            name="number",
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AddConstraint(
            model_name="partyround",
            constraint=models.UniqueConstraint(
                fields=("party", "number"), name="unique_party_round_number"
            ),
        ),
        migrations.AddField(
            model_name="partyround",
            name="closed_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("timeout", "tiempo agotado"),
                    ("stop", "detenida por un jugador"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.RunPython(backfill_closed_reasons, migrations.RunPython.noop),
    ]
